spring:
  datasource:
    url: jdbc:mysql://localhost:3306/iuroc
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 9999
mybatis:
  mapper-locations: classpath:mapper/*.xml